

- name: Create Docker Network
  become: true
  shell: "docker network create rabbits" 
  ignore_errors: yes

- name: Create Rabbit Cluster Node 1 
  become: true
  shell: "sudo docker run -d --rm --net rabbits -v /conf/rabbitmq/conf/rabbit-1/:/config/ -e RABBITMQ_CONFIG_FILE=/config/rabbitmq -e RABBITMQ_ERLANG_COOKIE=WIWVHCDTCIUAWANLMQAW --hostname rabbit-1 --name rabbit-1 -p 8081:15672 rabbitmq:3.8-management"
  ignore_errors: yes

- name: Create Rabbit Cluster Node 2 
  become: true
  shell: "sudo docker run -d --rm --net rabbits -v /conf/rabbitmq/conf/rabbit-2/:/config/ -e RABBITMQ_CONFIG_FILE=/config/rabbitmq -e RABBITMQ_ERLANG_COOKIE=WIWVHCDTCIUAWANLMQAW --hostname rabbit-2 --name rabbit-2 -p 8082:15672 rabbitmq:3.8-management"
  ignore_errors: yes

- name: Create Rabbit Cluster Node 3 
  become: true
  shell: "sudo docker run -d --rm --net rabbits -v /conf/rabbitmq/conf/rabbit-3/:/config/ -e RABBITMQ_CONFIG_FILE=/config/rabbitmq -e RABBITMQ_ERLANG_COOKIE=WIWVHCDTCIUAWANLMQAW --hostname rabbit-3 --name rabbit-3 -p 8083:15672 rabbitmq:3.8-management"
  ignore_errors: yes

- name: Start Rabbit Cluster Node 1 
  become: true
  shell: "sudo docker exec -it rabbit-1 rabbitmqctl start_app "
  ignore_errors: yes

- name: Create Rabbit Cluster Node 1 
  become: true
  shell: "sudo docker exec -it rabbit-1 rabbitmqctl cluster_status "
  ignore_errors: yes


# JOIN SLAVE 1
- name: Join Slave 1 - step 1
  become: true
  shell: "sudo docker exec -it rabbit-2 rabbitmqctl stop_app "
  ignore_errors: yes

- name: Join Slave 1 - step 2
  become: true
  shell: "sudo docker exec -it rabbit-2 rabbitmqctl reset "
  ignore_errors: yes

- name: Join Slave 1 - step 3
  become: true
  shell: "sudo docker exec -it rabbit-2 rabbitmqctl join_cluster rabbit@rabbit-1 "#
  ignore_errors: yes

- name: Join Slave 1 - step 4
  become: true
  shell: "sudo docker exec -it rabbit-2 rabbitmqctl start_app "
  ignore_errors: yes

- name: Join Slave 1 - step 5
  become: true
  shell: "sudo docker exec -it rabbit-2 rabbitmqctl cluster_status "
  ignore_errors: yes


