

- name: Create Docker Network
  become: true
  shell: "docker network create rabbits" 
  ignore_errors: yes

- name: Create Rabbit Cluster Node 1 
  become: true
  shell: "docker run -d --rm --net rabbits --hostname rabbit-1 --name rabbit-1 rabbitmq:3.8 "
  ignore_errors: yes

- name: Create Rabbit Cluster Node 2 
  become: true
  shell: "docker run -d --rm --net rabbits --hostname rabbit-2 --name rabbit-2 rabbitmq:3.8 "
  ignore_errors: yes

- name: Create Rabbit Cluster Node 3 
  become: true
  shell: "docker run -d --rm --net rabbits --hostname rabbit-3 --name rabbit-3 rabbitmq:3.8 "
  ignore_errors: yes

- name: Start Rabbit Cluster Node 1 
  become: true
  shell: "sudo docker exec -it rabbit-1 rabbitmqctl start_app "
  ignore_errors: yes

- name: Create Rabbit Cluster Node 1 
  become: true
  shell: "sudo docker exec -it rabbit-1 rabbitmqctl cluster_status "
  ignore_errors: yes


# JOIN SLAVE 1
- name: Join Slave 1 - step 1
  become: true
  shell: "sudo docker exec -it rabbit-2 rabbitmqctl stop_app "
  ignore_errors: yes

- name: Join Slave 1 - step 2
  become: true
  shell: "sudo docker exec -it rabbit-2 rabbitmqctl reset "
  ignore_errors: yes

- name: Join Slave 1 - step 3
  become: true
  shell: "sudo docker exec -it rabbit-2 rabbitmqctl join_cluster rabbit@rabbit-1 "#
  ignore_errors: yes

- name: Join Slave 1 - step 4
  become: true
  shell: "sudo docker exec -it rabbit-2 rabbitmqctl start_app "
  ignore_errors: yes

- name: Join Slave 1 - step 5
  become: true
  shell: "sudo docker exec -it rabbit-2 rabbitmqctl cluster_status "
  ignore_errors: yes

#
#
#
#
#
#
#





#- name: Create Rabbit Cluster Node 1 
#  become: true
#  shell: "sudo docker run -d --rm --net rabbits -v ${PWD}/rabbit-1/:/config/ -e RABBITMQ_CONFIG_FILE=/config/rabbitmq -e RABBITMQ_ERLANG_COOKIE=WIWVHCDTCIUAWANLMQAW --hostname rabbit-1 --name rabbit-1 -p 8081:15672 rabbitmq:3.8-management "

#- name: Create Rabbit Cluster Node 2 
#  become: true
#  shell: "sudo docker run -d --rm --net rabbits -v ${PWD}/rabbit-2/:/config/ -e RABBITMQ_CONFIG_FILE=/config/rabbitmq -e RABBITMQ_ERLANG_COOKIE=WIWVHCDTCIUAWANLMQAW --hostname rabbit-2 --name rabbit-2 -p 8082:15672 rabbitmq:3.8-management"

#- name: Create Rabbit Cluster Node 3 
#  become: true
#  shell: "sudo docker run -d --rm --net rabbits -v ${PWD}/rabbit-3/:/config/ -e RABBITMQ_CONFIG_FILE=/config/rabbitmq -e RABBITMQ_ERLANG_COOKIE=WIWVHCDTCIUAWANLMQAW --hostname rabbit-3 --name rabbit-3 -p 8083:15672 rabbitmq:3.8-management"


#- name: Create Rabbit Cluster Node 1 
#  become: true
#  shell: "sudo docker run -d --rm --net rabbits -v ${PWD}/config/rabbit-1/:/config/ -e RABBITMQ_CONFIG_FILE=/config/rabbitmq -e RABBITMQ_ERLANG_COOKIE=WIWVHCDTCIUAWANLMQAW --hostname rabbit-1 --name rabbit-1 -p 8081:15672 rabbitmq:3.8-management "

#- name: Create Rabbit Cluster Node 2 
#  become: true
#  shell: "sudo docker run -d --rm --net rabbits -v ${PWD}/config/rabbit-2/:/config/ -e RABBITMQ_CONFIG_FILE=/config/rabbitmq -e RABBITMQ_ERLANG_COOKIE=WIWVHCDTCIUAWANLMQAW --hostname rabbit-2 --name rabbit-2 -p 8082:15672 rabbitmq:3.8-management"

#- name: Create Rabbit Cluster Node 3 
#  become: true
#  shell: "sudo docker run -d --rm --net rabbits -v ${PWD}/config/rabbit-3/:/config/ -e RABBITMQ_CONFIG_FILE=/config/rabbitmq -e RABBITMQ_ERLANG_COOKIE=WIWVHCDTCIUAWANLMQAW --hostname rabbit-3 --name rabbit-3 -p 8083:15672 rabbitmq:3.8-management"

#- name: Federation Rabbit Cluster Node 1 
#  become: true
#  shell: "docker exec -it rabbit-1 rabbitmq-plugins enable rabbitmq_federation"

#- name: Federation Rabbit Cluster Node 2 
#  become: true
#  shell: "docker exec -it rabbit-2 rabbitmq-plugins enable rabbitmq_federation"

#- name: Federation Rabbit Cluster Node 3 
#  become: true
#  shell: "docker exec -it rabbit-3 rabbitmq-plugins enable rabbitmq_federation"


#sudo docker run -d --rm --net rabbits -v ${PWD}/rabbit-1/:/config/ -e RABBITMQ_CONFIG_FILE=/config/rabbitmq -e RABBITMQ_ERLANG_COOKIE=WIWVHCDTCIUAWANLMQAW --hostname rabbit-1 --name rabbit-1 -p 8081:15672 rabbitmq:3.8-management 
#- name: Create Rabbit Cluster Node 0 
#  become: true
#  shell: "sudo docker run -d --rm --net rabbits --hostname rabbit-1 --name rabbit-1 rabbitmq:3.8 "




#- name: Create Rabbit Cluster Node 1 
#  become: true
#  shell: "sudo docker run -d --rm --net rabbits --hostname rabbit-2 --name rabbit-2 rabbitmq:3.8 "

#- name: Create Rabbit Cluster Node 2 
#  become: true
#  shell: "sudo docker run -d --rm --net rabbits --hostname rabbit-3 --name rabbit-3 rabbitmq:3.8 "
 
#- name: Create Cluster Master 
#  become: true
#  shell: "sudo docker exec -it rabbit-1 rabbitmqctl cluster_status "





# JOIN SLAVE 1
# - name: Join Slave 1 - step 1
#  become: true
#   shell: "sudo docker exec -it rabbit-2 rabbitmqctl stop_app "

# - name: Join Slave 1 - step 2
#   become: true
#   shell: "sudo docker exec -it rabbit-2 rabbitmqctl reset "

#- name: Join Slave 1 - step 3
#  become: true
#  shell: "sudo docker exec -it rabbit-2 rabbitmqctl join_cluster rabbit@rabbit-1 "#

#- name: Join Slave 1 - step 4
#  become: true
#  shell: "sudo docker exec -it rabbit-2 rabbitmqctl start_app "

#- name: Join Slave 1 - step 5
#  become: true
#  shell: "sudo docker exec -it rabbit-2 rabbitmqctl cluster_status "





#- name: Join Slave 1
#  become: true
#  shell: |
#    docker exec -it rabbit-2 rabbitmqctl stop_app
#    docker exec -it rabbit-2 rabbitmqctl reset
#    docker exec -it rabbit-2 rabbitmqctl join_cluster rabbit@rabbit-1
#    docker exec -it rabbit-2 rabbitmqctl start_app
#    docker exec -it rabbit-2 rabbitmqctl cluster_status
#    exit 0

#- name: Join Slave 2
#  become: true
#  shell: |
#    docker exec -it rabbit-3 rabbitmqctl stop_app
#    docker exec -it rabbit-3 rabbitmqctl reset
#    docker exec -it rabbit-3 rabbitmqctl join_cluster rabbit@rabbit-1
#    docker exec -it rabbit-3 rabbitmqctl start_app
#    docker exec -it rabbit-3 rabbitmqctl cluster_status
#    exit 0



#docker network create rabbits
#docker run -d --rm --net rabbits --hostname rabbit-1 --name rabbit-1 rabbitmq:3.8 
#docker run -d --rm --net rabbits --hostname rabbit-2 --name rabbit-2 rabbitmq:3.8 
#docker run -d --rm --net rabbits --hostname rabbit-3 --name rabbit-3 rabbitmq:3.8 

#docker exec -it rabbit-1 rabbitmqctl cluster_status

#join node 2

#docker exec -it rabbit-2 rabbitmqctl stop_app
#docker exec -it rabbit-2 rabbitmqctl reset
#docker exec -it rabbit-2 rabbitmqctl join_cluster rabbit@rabbit-1
#docker exec -it rabbit-2 rabbitmqctl start_app
#docker exec -it rabbit-2 rabbitmqctl cluster_status

#join node 3
#docker exec -it rabbit-3 rabbitmqctl stop_app
#docker exec -it rabbit-3 rabbitmqctl reset
#docker exec -it rabbit-3 rabbitmqctl join_cluster rabbit@rabbit-1
#docker exec -it rabbit-3 rabbitmqctl start_app
#docker exec -it rabbit-3 rabbitmqctl cluster_status

#sudo docker run -d --rm --net rabbits -v ${PWD}/rabbit-1/:/config/ --hostname rabbit-1 --name rabbit-1 -p 8081:15672 rabbitmq:3.8-management 


#sudo docker exec -it rabbit-1 /bin/bash
